# Generated by Django 3.1 on 2020-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='human_answer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
