# Generated by Django 3.0.8 on 2020-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='tobacco_rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
