# Generated by Django 3.0.8 on 2020-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0002_auto_20200722_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='tobacco_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
